### Find All customer
GET http://localhost:8080/customers
Accept: application/json

### ADD NEW CUSTOMER
POST http://localhost:8080/customers
Content-Type: application/json

{
    "firstName" : "Ronakon45",
    "lastName" : "Watt"
}

### FIND SINGLE DATA
GET http://localhost:8080/customers/12
Content-Type: application/json

### UPDATE CUSTOMER DATA
PUT http://localhost:8080/customers/1
Content-Type: application/json

{
    "firstName" : "John",
    "lastName" : "Wattaa"
}

### DELETE CUSTOMER DATA
DELETE http://localhost:8080/customers/1
Content-Type: application/json
